/*----------------------------------------------------------------------------------------------------------------------
	-- 3. PRODUCT REPORT
	-- Answer the question:
	-- Which products are driving sales, profit, and quantity sold?
	----------------------------------------------------------------------------------

	PRODUCT METRIC               MEANING
	product_id                   Unique product
	product_name                 Product name
	category                     Product category
	sub_category                 Product sub-category
	total_orders                 Number of orders containing the product
	total_sales                  Revenue generated by the product
	total_profit                 Profit generated by the product
	total_quantity               Total units sold
	profit_margin_pct            Profitability percentage
	product_performance          High Performing, Mid-Range, or Low Performing
-------------------------------------------------------------------------------- */
 		-- PRODUCT REPORT 
WITH product_report AS 
(
	SELECT
		product_id, 
		product_name,
		category,
		sub_category,
		ROUND(SUM(sales),2)AS total_sales,
		ROUND(SUM(profit),2)AS total_profit,
		COUNT(DISTINCT order_id) AS total_orders,
		SUM(quantity) AS total_quantity,
		ROUND(SUM(profit) / SUM(sales)*100,2) AS profit_margin_pct,
        ROUND(AVG(SUM(sales))OVER(),2)AS avg_sales
	FROM superstore_sales
	GROUP BY 
		product_id,
		product_name,
		category,
		sub_category )

		SELECT
				product_id,
				product_name,
				category,
				sub_category,
				total_sales,
				total_profit,
				total_orders,
				total_quantity,
				profit_margin_pct,
                avg_sales,
                CASE
					WHEN total_sales > avg_sales THEN 'High Performance'
                    WHEN total_sales < avg_sales THEN 'Low Performance'
                    ELSE 'Mid-Range'
				END AS product_Performance
			FROM product_report
            ORDER BY total_sales DESC
;

/*--------------------------------------------------------------------------------------------------------------------*/

-- report_product_View
CREATE VIEW superstore_db_copy.Report_Products AS
	WITH product_report AS 
	(
		SELECT
			product_id, 
			product_name,
			category,
			sub_category,
			ROUND(SUM(sales),2)AS total_sales,
			ROUND(SUM(profit),2)AS total_profit,
			COUNT(DISTINCT order_id) AS total_orders,
			SUM(quantity) AS total_quantity,
			ROUND(SUM(profit) / SUM(sales)*100,2) AS profit_margin_pct,
			ROUND(AVG(SUM(sales))OVER(),2)AS avg_sales
		FROM superstore_sales
		GROUP BY 
			product_id,
			product_name,
			category,
			sub_category )

			SELECT
					product_id,
					product_name,
					category,
					sub_category,
					total_sales,
					total_profit,
					total_orders,
					total_quantity,
					profit_margin_pct,
					avg_sales,
					CASE
						WHEN total_sales > avg_sales THEN 'High Performance'
						WHEN total_sales < avg_sales THEN 'Low Performance'
						ELSE 'Mid-Range'
					END AS product_Performance
				FROM product_report
				ORDER BY total_sales DESC
;